version: "3.9"

services:
  jowl:
    build:
      context: .
      dockerfile: Dockerfile
    image: jowl:latest
    container_name: jowl
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - C:\:/usr/src/app/dir-in-container
