version: "3"

services:
  jowl:
    build:
      context: .
      dockerfile: Dockerfile
    image: jowl:latest
    container_name: jowl
    restart: always
    ports:
      - "9170:9170"
    networks:
      - slsdev

  virtuoso:
    image: askomics/virtuoso:7.2.7
    container_name: virtuoso
    environment:
      DBA_PASSWORD: "dba"
      SPARQL_UPDATE: "true"
    ports:
      - 8890:8890
    volumes:
      - ../data/virtuoso:/data
    networks:
      - slsdev

networks:
  slsdev:
    driver: bridge
    labels:
        - "com.docker.compose.project=slsdev"
