version: "3"

services:
  jowl:
    build:
      context: .
      dockerfile: Dockerfile
    image: jowl:latest
    container_name: jowl
    restart: always
    ports:
      - "9170:9170"
    environment:
      - JDBC_URL= ${JDBC_URL}
      - JDBC_USER= ${JDBC_USER}
      - JDBC_PASSWORD= ${JDBC_PASSWORD}
      - JDBC_DRIVER= ${JDBC_DRIVER}

